jobs:
  include:
        before_script:
          -cd BackEndModeules
      - language: python
        python: 3.8
        install:
          - pip install -r requirements.txt
        "script": [
          "echo \"skipping tests\""
        ]
       
      - language: node_js
        node_js:
          - "stable"
        script:
          - npm test
