jobs:
  include:
        before_script:
          -cd BackendModeules
      - language: python
        python: 3.8
        script:
          - echo "skipping tests"
        before_script:
          -cd 
      - language: node_js
        node_js:
          - "stable"
        script:
          - npm test
